
categories:
  - "mobs"
  - "ores"

shop:
  color:
    items:
      vanilla: "<gold>"
      custom: "<gold>"
  ingredients:
    - "B;LIGHT_BLUE_STAINED_GLASS_PANE"
    - "G;LIME_STAINED_GLASS_PANE"
  shape:
    - "GGBBBBBGG"
    - "G       G"
    - "B       B"
    - "B       B"
    - "G       G"
    - "GGBBBBBGG"
