categories:
  - "mobs"
  - "ores"

shop:
  itemsColor: "<gold>"
  ingredient:
    - "B;LIGHT_BLUE_STAINED_GLASS_PANE"
    - "G;LIME_STAINED_GLASS_PANE"
  shape:
    - "GGBBBBBGG"
    - "G       G"
    - "B       B"
    - "B       B"
    - "G       G"
    - "GGBBBBBGG"


#shop:
#   itemsColor:
#     enable: true
#     color: <gold>
#   customItemsColor:
#     enable: true
#     color: <default> // <gold>
#
