
categories:
  - "mobs"
  - "ores"

shop:
  itemsColor: "<gold>"
  color:
    items:
      enabled: true
      color: "<gold>"
    customItems:
      enabled: true
      color: "<gold>"
  ingredients:
    - "B;LIGHT_BLUE_STAINED_GLASS_PANE"
    - "G;LIME_STAINED_GLASS_PANE"
  shape:
    - "GGBBBBBGG"
    - "G       G"
    - "B       B"
    - "B       B"
    - "G       G"
    - "GGBBBBBGG"
