
categories:
  - "mobs"
  - "ores"
  - "blocks"
  - "food_farm"

shop:
  color:
    items:
      vanilla: "<gold>"
      custom: "<gold>"
  ingredients:
    - "A;LIGHT_BLUE_STAINED_GLASS_PANE"
    - "B;LIME_STAINED_GLASS_PANE"
  shape:
    - "BBAAAAABB"
    - "B       B"
    - "A       A"
    - "A       A"
    - "B       B"
    - "BBAAAAABB"

sell_gui:
  title: "<#00aeff>Sell Menu"
  ingredients:
    - "A;LIGHT_BLUE_STAINED_GLASS_PANE"
    - "B;LIME_STAINED_GLASS_PANE"
  shape:
    - "BBAAAAABB"
    - "B       B"
    - "A       A"
    - "A       A"
    - "B       B"
    - "BBAAAAABB"

main_gui:
  title: "<#00aeff>Shop"
  ingredients:
    - "A;LIGHT_BLUE_STAINED_GLASS_PANE"
    - "B;LIME_STAINED_GLASS_PANE"
    - "C;BLACK_STAINED_GLASS_PANE"
    - "D;GRAY_STAINED_GLASS_PANE"
  shape:
    - "BBAAAAABB"
    - "BCCDDDCCB"
    - "AC     CA"
    - "ACD   DCA"
    - "BCCDDDCCB"
    - "BBAAAAABB"
  profile:
    display_name: "<yellow><player> Information: "
    lore:
      - "<aqua>Balance: <green><balance>"
    slot: 49
  categories:
    blocks:
      display_name: "<green>Blocks"
      material: GRASS_BLOCK
      slot: 20
    food_farm:
      display_name: "<green>Food & Farm"
      material: COOKED_PORKCHOP
      slot: 21
    mobs:
      display_name: "<green>Mobs drop"
      material: ROTTEN_FLESH
      slot: 22
    ores:
      display_name: "<green>Ores"
      material: DIAMOND
      slot: 23