name: PalladiumShop
version: '${version}'
main: ir.syphix.palladiumshop.PalladiumShop
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    PalladiumItems:
      load: BEFORE
      required: false
    Slimefun:
      load: BEFORE
      required: false
    WildTools:
      load: BEFORE
      required: false
    ItemsAdder:
      load: BEFORE
      required: false
api-version: '1.19'
